<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'RimAI.Communication.Relations'">
    <BaseOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Relations\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Relations\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'RimAI.Communication.Relations.Tests'">
    <BaseOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Relations.Tests\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(LOCALAPPDATA)\Ustas\RimWorldSourceBuilds\RimAI.Communication.Relations.Tests\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
