using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using RimWorld;
using RimWorld.Planet;
using UnityEngine;
using Verse;
using Verse.Sound;
using Ustas.RimAI.Communication.Relations.AI;
using Ustas.RimAI.Communication.Relations.Config;
using Ustas.RimAI.Communication.Relations.Context;
using Ustas.RimAI.Communication.Relations.Dialogue;
using Ustas.RimAI.Communication.Relations.DiplomacySystem;
using Ustas.RimAI.Communication.Relations.Guards;
using Ustas.RimAI.Communication.Relations.Memory;
using Ustas.RimAI.Communication.Relations.Module;
using Ustas.RimAI.Communication.Relations.PawnRpgPush;
using Ustas.RimAI.Communication.Relations.Persistence;
using Ustas.RimAI.Communication.Relations.Prompting;
using Ustas.RimAI.Communication.Relations.UI;

namespace Ustas.RimAI.Communication.Relations.UI;

internal sealed class DiplomacyDialogueParts
{
    internal readonly Dialog_DiplomacyDialogue Owner;
    internal readonly DiplomacyDialogueActionHint ActionHint;
    internal readonly DiplomacyAirdropPendingPolicy AirdropPending;
    internal readonly DiplomacyActionPolicyService Policy;
    internal readonly DiplomacyActionClarificationService Clarify;
    internal readonly DiplomacyDialogueAlbumActions Album;
    internal readonly DiplomacySessionApplication Session;
    internal readonly DiplomacyDialoguePresenter Presenter;
    internal readonly DiplomacyDialogueChrome Chrome;
    internal readonly DiplomacyDialogueFactionList FactionList;
    internal readonly DiplomacyDialogueMessageView MessageView;
    internal readonly DiplomacyDialogueInput Input;
    internal readonly DiplomacySendInfoWorkflow SendInfo;
    internal readonly DiplomacySessionPromptBuilder SessionPrompt;
    internal readonly DiplomacySessionOutcomeMessages Outcomes;
    internal readonly DiplomacyDialogueFallback Fallback;
    internal readonly DiplomacyAirdropWorkflow Airdrop;
    internal readonly DiplomacyDialogueQuickActions QuickActions;
    internal readonly DiplomacyDialogueHoverCard HoverCard;
    internal readonly DiplomacyImageActionWorkflow ImageAction;
    internal readonly DiplomacyDialogueImageCache ImageCache;
    internal readonly DiplomacyDialogueImageBubbles ImageBubbles;
    internal readonly DiplomacyDialogueAirdropCards AirdropCards;
    internal readonly DiplomacyAirdropAsyncWorkflow AirdropAsync;
    internal readonly DiplomacyPeaceWorkflow Peace;
    internal readonly DiplomacySocialCircleActions SocialActions;
    internal readonly DiplomacyMemorySyncCoordinator MemorySync;
    internal readonly DiplomacyDialogueMessageLayout MessageLayout;
    internal readonly DiplomacyPresenceCoordinator Presence;
    internal readonly DiplomacyRansomProofExport RansomExport;
    internal readonly DiplomacyRansomBatchRuntime RansomBatch;
    internal readonly DiplomacyRansomProofWorkflow RansomProof;
    internal readonly DiplomacyRansomSelectionWorkflow RansomSelect;
    internal readonly DiplomacyRequestFeedback Feedback;
    internal readonly DiplomacyGiftWorkflow Gift;
    internal readonly DiplomacyDialogueSocialCircleView SocialView;
    internal readonly DiplomacyDialogueSpeakers Speakers;
    internal readonly DiplomacyDialogueStrategyUi StrategyUi;
    internal readonly DiplomacyDialogueStrategyRequest StrategyRequest;
    internal readonly DiplomacyDialogueStrategyPrompt StrategyPrompt;
    internal readonly DiplomacyAirdropConfirmationUi AirdropConfirmUi;
    internal readonly DiplomacyDialogueStrategyContext StrategyContext;
    internal readonly DiplomacyDialogueHoverCardDraw HoverCardDraw;
    internal readonly DiplomacyDialogueInputHost InputHost;
    internal readonly DiplomacyDialogueTypingStatus Typing;

    internal DiplomacyDialogueParts(Dialog_DiplomacyDialogue owner)
    {
        Owner = owner;
        ActionHint = new DiplomacyDialogueActionHint(owner);
        AirdropPending = new DiplomacyAirdropPendingPolicy(owner);
        Policy = new DiplomacyActionPolicyService(owner);
        Clarify = new DiplomacyActionClarificationService(owner);
        Album = new DiplomacyDialogueAlbumActions(owner);
        Session = new DiplomacySessionApplication(owner);
        Presenter = new DiplomacyDialoguePresenter(owner);
        Chrome = new DiplomacyDialogueChrome(owner);
        FactionList = new DiplomacyDialogueFactionList(owner);
        MessageView = new DiplomacyDialogueMessageView(owner);
        Input = new DiplomacyDialogueInput(owner);
        SendInfo = new DiplomacySendInfoWorkflow(owner);
        SessionPrompt = new DiplomacySessionPromptBuilder(owner);
        Outcomes = new DiplomacySessionOutcomeMessages(owner);
        Fallback = new DiplomacyDialogueFallback(owner);
        Airdrop = new DiplomacyAirdropWorkflow(owner);
        QuickActions = new DiplomacyDialogueQuickActions(owner);
        HoverCard = new DiplomacyDialogueHoverCard(owner);
        ImageAction = new DiplomacyImageActionWorkflow(owner);
        ImageCache = new DiplomacyDialogueImageCache(owner);
        ImageBubbles = new DiplomacyDialogueImageBubbles(owner);
        AirdropCards = new DiplomacyDialogueAirdropCards(owner);
        AirdropAsync = new DiplomacyAirdropAsyncWorkflow(owner);
        Peace = new DiplomacyPeaceWorkflow(owner);
        SocialActions = new DiplomacySocialCircleActions(owner);
        MemorySync = new DiplomacyMemorySyncCoordinator(owner);
        MessageLayout = new DiplomacyDialogueMessageLayout(owner);
        Presence = new DiplomacyPresenceCoordinator(owner);
        RansomExport = new DiplomacyRansomProofExport(owner);
        RansomBatch = new DiplomacyRansomBatchRuntime(owner);
        RansomProof = new DiplomacyRansomProofWorkflow(owner);
        RansomSelect = new DiplomacyRansomSelectionWorkflow(owner);
        Feedback = new DiplomacyRequestFeedback(owner);
        Gift = new DiplomacyGiftWorkflow(owner);
        SocialView = new DiplomacyDialogueSocialCircleView(owner);
        Speakers = new DiplomacyDialogueSpeakers(owner);
        StrategyUi = new DiplomacyDialogueStrategyUi(owner);
        StrategyRequest = new DiplomacyDialogueStrategyRequest(owner);
        StrategyPrompt = new DiplomacyDialogueStrategyPrompt(owner);
        AirdropConfirmUi = new DiplomacyAirdropConfirmationUi(owner);
        StrategyContext = new DiplomacyDialogueStrategyContext(owner);
        HoverCardDraw = new DiplomacyDialogueHoverCardDraw(owner);
        InputHost = new DiplomacyDialogueInputHost(owner);
        Typing = new DiplomacyDialogueTypingStatus(owner);
    }
}
